Fix an error C2666 in ccHObject.h. (#842)
* Fix a error C2666 in ccHObject.h

* Use static_cast instead of C-style cast for error C2666 in ccHObject.h.